### ISSUE TITLE
Weird rotation after teleportation

### ISSUE THREAD

**Issue by Folas1337** [devblook/backloc#2]
After teleporting the rotation of the moment after death seems to be recorded, resulting in something like this when clicking on the teleport button while having the chat open.
![image](https://github.com/devblook/backloc/assets/39222968/4e88eeb0-0fd4-4515-8734-0b43a412a46a)

It returns to normal once you close chat but perhaps ideally you don't want to save the rotation of the player and instead only the coordinates (x, y and z) :D

**Comment by BryanGmG** [comment]
Hi, the plugin saves the exact location including the rotation of the camera, in the next update I will create an option that by default does not save the rotation.
